services:
  mysql:
    image: postgres:latest
    container_name: local-postgres
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${POST_ROOT_PASSWORD}
      MYSQL_DATABASE: ${POST_DATABASE}
      MYSQL_USER: ${POST_USER}
      MYSQL_PASSWORD: ${POST_PASSWORD}
    ports:
      - '${POST_PORT}:5432'
    networks:
      - springboot-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  springboot-network:
    driver: bridge