server:
  jackson:
    property-naming-strategy: SNAKE_CASE
  port: 8089
  servlet:
    encoding:
      charset: UTF-8

# jpa 설정
spring:
  application:
    name: old
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:log4jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.old.dto